from __future__ import annotations

import os
from pathlib import Path
from typing import Mapping

from .cmake_presets import load_or_init_user_presets, upsert_configure_preset, write_user_presets
from .proc import die, note


EXTERNAL_PRESET_PREFIX = "devstack-external-"
SANDBOX_PRESET_PREFIX = "devstack-sandbox-"


def external_build_path(root: Path, preset: str, env: Mapping[str, str]) -> Path:
    configured = env.get("DEVSTACK_BUILD_ROOT", "").strip()
    if not configured:
        die("--sandbox-paths requires DEVSTACK_BUILD_ROOT")
    build_root = Path(configured).expanduser()
    if not build_root.is_absolute():
        die("DEVSTACK_BUILD_ROOT must be an absolute path")
    return build_root.resolve() / root.resolve().name / "sandbox" / preset


def ensure_sandbox_build_preset(root: Path, preset: str, binary_dir: str) -> str:
    if preset.startswith(SANDBOX_PRESET_PREFIX):
        return preset
    name = f"{SANDBOX_PRESET_PREFIX}{preset}"
    user = load_or_init_user_presets(root)
    upsert_configure_preset(
        user,
        {
            "name": name,
            "displayName": f"Stable-path {preset} (generated by devstack)",
            "description": "Runs inside Devstack's stable-path build namespace.",
            "inherits": [preset],
            "binaryDir": binary_dir,
        },
    )
    write_user_presets(root, user)
    return name


def ensure_external_build_preset(
    root: Path, preset: str, env: Mapping[str, str] | None = None
) -> str:
    """Return a CMake preset whose binary directory lives under DEVSTACK_BUILD_ROOT."""
    values = os.environ if env is None else env
    configured = values.get("DEVSTACK_BUILD_ROOT", "").strip()
    if not configured:
        return preset

    build_root = Path(configured).expanduser()
    if not build_root.is_absolute():
        die("DEVSTACK_BUILD_ROOT must be an absolute path")
    build_root = build_root.resolve()

    root = root.resolve()
    if not root.name:
        die(f"cannot derive worktree name from repository root: {root}")

    if preset.startswith(EXTERNAL_PRESET_PREFIX):
        return preset

    external_name = f"{EXTERNAL_PRESET_PREFIX}{preset}"
    target = build_root / root.name / preset
    user = load_or_init_user_presets(root)
    upsert_configure_preset(
        user,
        {
            "name": external_name,
            "displayName": f"External {preset} (generated by devstack)",
            "description": "Stores generated build files outside the source worktree.",
            "inherits": [preset],
            "binaryDir": str(target),
        },
    )
    write_user_presets(root, user)
    note(f"external build dir: {target}")
    return external_name
